version: 0.0
os: linux
files:
  - source: /deployment
    destination: /home/ubuntu/NBE5-7-2-TEAM08/deployment
    overwrite: yes
  - source: /scripts
    destination: /home/ubuntu/NBE5-7-2-TEAM08/scripts
    overwrite: yes
  - source: /docker-compose.yml
    destination: /home/ubuntu
    overwrite: yes

permissions:
  - object: /home/ubuntu/NBE5-7-2-TEAM08/deployment
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/deploy_hook.sh
      timeout: 300
      runas: ubuntu
